### ISSUE TITLE
Error when used with ParseReact

### ISSUE THREAD

**Issue by jaredpalmer** [petehunt/react-cli#10]
I'm having some trouble using it with ParseReact (building a larger app). After running `rwb static` I'm getting this error:

``` shell
/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse/lib/browser/StorageController.browser.js:24
    return localStorage.getItem(path);
           ^
ReferenceError: localStorage is not defined
    at Object.e.exports.getItem (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse/lib/browser/StorageController.browser.js:24:12)
    at Object.e.exports.getItemAsync (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse/lib/browser/Storage.js:43:52)
    at Object.e.exports.currentInstallationId (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse/lib/browser/InstallationController.js:44:33)
    at Object.v.request (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse/lib/browser/RESTController.js:176:35)
    at Object.u.default.setQueryController.find (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse/lib/browser/ParseQuery.js:1138:27)
    at e.o.value (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse/lib/browser/ParseQuery.js:289:25)
    at e.s.value (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse-react/lib/browser/Subscription.js:145:26)
    at new e (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse-react/lib/browser/Subscription.js:94:10)
    at Object.r [as subscribeToQuery] (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse-react/lib/browser/SubscriptionManager.js:47:20)
    at e.p.subscribe (/Users/jaredpalmer/workspace/github/shellypalmer/blah/node_modules/parse-react/lib/browser/ParsePatches.js:53:32)
```

This project is awesome btw.

**Comment by petehunt** [comment]
`rwb` isn't designed to shim the browser. This is consistent with most server-side-rendering implementations for React. I'd suggest opening an issue on `ParseReact` to support running in a `nodejs` environment.
