### ISSUE TITLE
Cannot find module myapp/init

### ISSUE THREAD

**Issue by winkler1** [petehunt/react-cli#2]
Should this be installed with -g? The 4-line example mkdir/init does not mention. Getting this error--

```
$ md myapp
~/repos/myapp
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.
...
Is this ok? (yes) 

~/repos/myapp
$ npm install -g react-cli
npm WARN deprecated react-tools@0.11.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
/usr/local/bin/react-cli -> /usr/local/lib/node_modules/react-cli/bin/react
react-cli@0.2.0 /usr/local/lib/node_modules/react-cli
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── react@0.12.2 (envify@3.4.0)
└── node-jsx@0.11.0 (react-tools@0.11.2)
~/repos/myapp
$ react-cli init
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/Jeff/repos/myapp/init'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.render (/usr/local/lib/node_modules/react-cli/lib/facade.js:9:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-cli/bin/react:14:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by petehunt** [comment]
That's the wrong `react-cli`. I'm looking for a better name -- suggestions welcome.

`npm install -g petehunt/react-cli`

**Comment by winkler1** [comment]
ah- duh. Perhaps "clir" (command-line-react)? short/available.
